// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTAcaSs3Jt24aP8S3-9mdxS1Stw7cfHGE',
    appId: '1:320872379970:web:6577f65a21bf8dd4135fdb',
    messagingSenderId: '320872379970',
    projectId: 'adhkar-371fb',
    authDomain: 'adhkar-371fb.firebaseapp.com',
    storageBucket: 'adhkar-371fb.appspot.com',
    measurementId: 'G-4F7CY204TT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-8ymXSjs4QxmaSsELx0ls6rEn2nBFaLQ',
    appId: '1:320872379970:android:8afa1fa257fb8483135fdb',
    messagingSenderId: '320872379970',
    projectId: 'adhkar-371fb',
    storageBucket: 'adhkar-371fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9FgEL4eu0iOAeLEHJRQXQYW86kjIhg8Y',
    appId: '1:320872379970:ios:36529e6904975f4b135fdb',
    messagingSenderId: '320872379970',
    projectId: 'adhkar-371fb',
    storageBucket: 'adhkar-371fb.appspot.com',
    iosBundleId: 'com.example.adhkar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9FgEL4eu0iOAeLEHJRQXQYW86kjIhg8Y',
    appId: '1:320872379970:ios:1e1453590711edc3135fdb',
    messagingSenderId: '320872379970',
    projectId: 'adhkar-371fb',
    storageBucket: 'adhkar-371fb.appspot.com',
    iosBundleId: 'com.example.adhkar.RunnerTests',
  );
}
